version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: happyice-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: happyice
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - happyice-net

  backend:
    build: ./backend
    container_name: happyice-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: happyice
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - happyice-net

  frontend:
    build: ./frontend
    container_name: happyice-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - happyice-net

volumes:
  pgdata:

networks:
  happyice-net:
    driver: bridge
